namespace LMVideoStudio.Host

open System
open System.IO
open System.Text
open LMVideoStudio.Domain

module SharePackExport =
    let SharePackRelativeDir = "exports/share-pack"

    type SharePackPreset =
        { Name: string
          FileName: string
          Width: int
          Height: int
          Notes: string }

    let presets =
        [ { Name = "YouTube"
            FileName = "youtube_16x9.mp4"
            Width = 1920
            Height = 1080
            Notes = "16:9 landscape — upload as main video or Shorts landscape." }
          { Name = "Reels"
            FileName = "reels_9x16.mp4"
            Width = 1080
            Height = 1920
            Notes = "9:16 vertical — Instagram Reels, TikTok, YouTube Shorts." } ]

    type SharePackResult =
        { OutputDir: string
          Files: string list
          CaptionPath: string
          ReadmePath: string }

    let private writeCaption (project: Project) (path: string) =
        let lines =
            [ "# Share caption stub"
              ""
              $"Project: {project.Name}"
              ""
              match project.Brief with
              | Some b when not (String.IsNullOrWhiteSpace b) -> b
              | _ -> "Add your hook, hashtags, and CTA here."
              ""
              "#LMVideoStudio" ]

        File.WriteAllLines(path, lines, Encoding.UTF8)

    let private writeReadme (project: Project) (path: string) (files: string list) =
        let fileList =
            files
            |> List.map (fun f -> $"- `{f}`")
            |> String.concat Environment.NewLine

        let presetNotes =
            presets
            |> List.map (fun p -> $"- **{p.Name}** ({p.Width}x{p.Height}): {p.Notes}")
            |> String.concat Environment.NewLine

        let text =
            $"""# Share Pack — {project.Name}

Generated by LMVideoStudio. Upload manually or connect OAuth in Settings for direct upload.

## Included files

{fileList}
- `caption.txt` — edit before posting

## Presets

{presetNotes}

## Tips

1. Review mockup/bake timing before posting.
2. Replace caption stub with platform-specific copy.
3. Keep brand colors from style pack consistent in thumbnails.
"""

        File.WriteAllText(path, text, Encoding.UTF8)

    let exportSharePack (repoRoot: string) (projectFolder: string) (project: Project) =
        let sourceCandidates =
            [ Path.Combine(projectFolder, ExportJobs.BakeRelativePath.Replace('/', Path.DirectorySeparatorChar))
              Path.Combine(projectFolder, ExportJobs.PreviewRelativePath.Replace('/', Path.DirectorySeparatorChar)) ]

        match sourceCandidates |> List.tryFind File.Exists with
        | None -> Error "No preview or bake MP4 found — run mockup preview or bake first"
        | Some sourcePath ->
            let outDir = Path.Combine(projectFolder, SharePackRelativeDir.Replace('/', Path.DirectorySeparatorChar))
            Directory.CreateDirectory outDir |> ignore

            let exported =
                presets
                |> List.choose (fun preset ->
                    let dest = Path.Combine(outDir, preset.FileName)

                    let args =
                        [ "-y"
                          "-nostdin"
                          "-i"; sourcePath
                          "-vf"; $"scale={preset.Width}:{preset.Height}:force_original_aspect_ratio=decrease,pad={preset.Width}:{preset.Height}:(ow-iw)/2:(oh-ih)/2"
                          "-c:v"; "libx264"
                          "-preset"; "fast"
                          "-pix_fmt"; "yuv420p"
                          dest ]

                    match FfmpegExport.runFfmpeg repoRoot args None with
                    | Ok _ when File.Exists dest -> Some preset.FileName
                    | _ -> None)

            if List.isEmpty exported then
                Error "FFmpeg failed to render share-pack presets"
            else
                let captionPath = Path.Combine(outDir, "caption.txt")
                let readmePath = Path.Combine(outDir, "README.md")
                writeCaption project captionPath
                writeReadme project readmePath exported

                Ok
                    { OutputDir = SharePackRelativeDir
                      Files = exported
                      CaptionPath = Path.Combine(SharePackRelativeDir, "caption.txt").Replace('\\', '/')
                      ReadmePath = Path.Combine(SharePackRelativeDir, "README.md").Replace('\\', '/') }
